name: lensia_app_project
description: A new Flutter project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  app_links: ^7.0.0
  image_picker: ^1.2.1
  video_player: ^2.8.3
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay-Regular.ttf