// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr2PLn5r8KqN3KmipAqEnEpBzu65Yk434',
    appId: '1:606190695428:web:fee401a37fc14a44d8b151',
    messagingSenderId: '606190695428',
    projectId: 'lensia-719ae',
    authDomain: 'lensia-719ae.firebaseapp.com',
    storageBucket: 'lensia-719ae.firebasestorage.app',
    measurementId: 'G-84JL4EMEF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4ViHShme_D3LU4eOUSUbC5U75NARv1F8',
    appId: '1:606190695428:android:b2d0a60aa668dba8d8b151',
    messagingSenderId: '606190695428',
    projectId: 'lensia-719ae',
    storageBucket: 'lensia-719ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE346IsYwaIxWgpYp7sYX3sC2yjZa3CJU',
    appId: '1:606190695428:ios:2c8dae5e613e82ebd8b151',
    messagingSenderId: '606190695428',
    projectId: 'lensia-719ae',
    storageBucket: 'lensia-719ae.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE346IsYwaIxWgpYp7sYX3sC2yjZa3CJU',
    appId: '1:606190695428:ios:2c8dae5e613e82ebd8b151',
    messagingSenderId: '606190695428',
    projectId: 'lensia-719ae',
    storageBucket: 'lensia-719ae.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr2PLn5r8KqN3KmipAqEnEpBzu65Yk434',
    appId: '1:606190695428:web:99717c8713521517d8b151',
    messagingSenderId: '606190695428',
    projectId: 'lensia-719ae',
    authDomain: 'lensia-719ae.firebaseapp.com',
    storageBucket: 'lensia-719ae.firebasestorage.app',
    measurementId: 'G-1XS1ZPLHH5',
  );
}
